routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']],
    function () {

        Route::get('/', 'HomeController@index');
        //reset password
        Route::get('/reset-password/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Auth::routes();
        Route::get('/get/job', 'Frontend\JobsController@getJob');
        Route::get('/register', 'RegistrationController@registerForm')->name('user.register_form_step_1');
        Route::get('/register/organization', 'RegistrationController@registerOrganizationForm')->name('user.register_form_step_2_organization')->middleware('auth');
        Route::get('/register/individual', 'RegistrationController@registerIndividualForm')->name('user.register_form_step_2_individual')->middleware('auth');
        Route::post('/register-final/{id}', 'RegistrationController@register_final')->name('user.register_final');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/jobs/{slug?}/{type?}/{view?}', 'Frontend\JobsController@index')->name('jobs');
        Route::post('/job/{id}/clone', ['as' => 'jobs.clone', 'uses' => 'JobController@clone']);
        Route::get('/blog', 'Frontend\BlogsController@index')->name('blog');
        Route::get('/blog/{slug}', 'Frontend\BlogsController@show')->name('blog-single');
        Route::get('/review', 'Frontend\ReviewsController@index')->name('review');
        Route::get('/links', 'Frontend\ResourceController@index')->name('resource.index');
        Route::get('/about', 'HomeController@about')->name('about');
        Route::get('/contact', 'HomeController@contact')->name('contact');
        Route::get('/company/{slug}', 'HomeController@companySingle')->name('companySingle');


        //my-profile
        Route::group(['prefix' => 'profile', 'middleware' => ['auth', 'permission:profile', 'closedUser']], function () {
            Route::resource('permission', 'PermissionController')->middleware(['permission:give_permissions']);;
            Route::post('/permissions/update', ['as' => 'permissionsUpdate', 'uses' => 'PermissionController@permissionsUpdate']);
            Route::get('/make/announcement/{type}/{job_id?}', 'JobController@create')->name('make-job')->middleware(['permission:create_announcement']);
            Route::get('/announcements/{id}/edit/{translate?}', 'JobController@edit')->name('announcements-edit')->middleware(['permission:edit_announcement']);
//

            Route::resource('announcements', 'JobController')->except(['edit'])->middleware(['permission:create_announcement|delete_announcement']);
            Route::resource('resource_category', 'ResourceCategoryController')->middleware(['permission:resourceCategory_resources']);

            Route::post('/change/status/{id}', 'JobController@changeStatus')->name('status-change');
            Route::post('/after/preview/{id}', 'JobController@afterPreview')->name('after-preview');
            Route::post('/change/resource/status/{id}', 'ResourceController@changeStatus')->name('status-change-resource');
            Route::post('/change/blog/status/{id}', 'BlogController@changeStatus')->name('status-change-blog');
            Route::resource('reviews', 'ReviewController')->middleware(['permission:create_review|edit_review|delete_review']);
            Route::resource('blogs', 'BlogController')->middleware(['permission:create_article|edit_article|delete_article']);
            Route::resource('users', 'UserController')->middleware(['permission:create_user|edit_user|delete_user|close_user']);
            Route::resource('resources', 'ResourceController')->middleware(['permission:create_resource|delete_resource|edit_resource']);
            Route::resource('appliers', 'AppliersController');
            Route::get('/appliers/show/details/applier/{id}', ['as' => 'appliers.show-details', 'uses' => 'AppliersController@showDetails']);
            Route::post('/change/applier/status/{id}', 'AppliersController@changeStatus')->name('applier-status-change');
            Route::post('/user/change/status/{id}', 'UserController@changeStatus')->name('user-status-change');
            Route::post('/invoice/change/status/{id}', 'InvoiceController@changeStatus')->name('invoice-status-change');

            Route::resource('resume', 'CvController')->except(['create'])->middleware(['permission:create_resume|edit_resume|delete_resume']);
            Route::get('/create/resume/{id?}', ['as' => 'resume.create', 'uses' => 'CvController@create', 'middleware' => ['permission:create_resume|edit_resume']]);

            Route::resource('subscribtion', 'SubscribeController')->middleware(['permission:subscribtions']);
            Route::resource('pages', 'PageController')->middleware(['permission:create_pages|edit_pages|delete_pages']);
            Route::get('/register/organization/{id}', 'UserController@registerOrganizationForm')->name('profile.register_form_step_2_organization');
            Route::get('/register/individual/{id}', 'UserController@registerIndividualForm')->name('profile.register_form_step_2_individual');
            Route::post('/user/register/step-1', 'UserController@registerStep1')->name('registerUserStep1');
            Route::post('/user/register/step-2/{id}', 'UserController@registerStep2')->name('registerUserStep2');
            Route::patch('/change_password/{id}', 'UserController@changePassword')->name('changeUserPassword');
            Route::patch('/update_bankDetails/{id}', 'UserController@bankDetails')->name('bankDetails')->middleware(['permission:changeBankDetails_user']);;
            Route::get('/register/organization/{id}', 'UserController@registerOrganizationForm')->name('profile.register_form_step_2_organization');
            Route::get('/users/permissions/{id}', 'UserController@editPermissions')->name('user-permission');
            Route::patch('/permissions/update/{id}', 'UserController@updatePermissions')->name('user-permission-update');
            Route::patch('/connect', 'UserController@connectToOrganization')->name('connect_organization');
            Route::get('/', 'ProfileController@index')->name('profile');
            Route::post('/image', 'ProfileController@profileImage')->name('profile-image');
            Route::get('/resume-pdf/{id}', 'CvController@resumePdf')->name('resumePDF');
            Route::get('/invoice-pdf/{id}', 'InvoiceController@invoicePdf')->name('invoicePDF');
            Route::get('/login/users/{id}/{origin?}', 'UserController@loginUser')->name('usersLogin');
            Route::resource('service_category', 'ServiceCategoryController')->middleware(['permission:serviceCategory_service']);
            Route::resource('services', 'ServiceController')->middleware(['permission:create_service|edit_service|delete_service|all_service']);


            Route::resource('invoice', 'InvoiceController')->middleware(['permission:create_invoice|edit_invoice|delete_invoice|all_invoice']);
            Route::get('/create/invoice', 'InvoiceController@createInvoiceStep1')->name('createInvoiceStep1')->middleware(['permission:create_invoice|edit_invoice|delete_invoice|all_invoice']);
            Route::get('/search/resume', 'SearchResumeController@index')->name('searchResume');


        });
        Route::group(['middleware' => ['auth', 'closedUser']], function () {
            Route::post('/apply', 'Frontend\JobsController@apply')->name('apply');
            Route::get('/apply/job/{slug}', 'Frontend\JobsController@applyJob')->name('applyJob');
            Route::post('/get_language', 'CvController@getLanguage');
            Route::post('/cv_language', 'CvController@language');
            Route::post('/cv_visa', 'CvController@visa');
            Route::post('/get_visa', 'CvController@getVisa');
            Route::post('/remove/attachment', 'JobController@removeAttachment');
            Route::post('/get/sub_category', 'ResourceController@getSubcategory')->name('getSubCategory');
        });

        Route::get('/404', function () {
            return view('404');
        });


        Route::get('/cv/{id}', 'CvController@showCv')->name('showCv');
        Route::get('/{page}', 'Frontend\PageController@index')->name('pages');


    });

Route::get('/translations', ['as' => 'translation_manager', 'uses' => '\Barryvdh\TranslationManager\Controller@getIndex'])->middleware(['permission:translate', 'auth']);
Route::get('/translations/view/{group?}', ['as' => 'translation_group', 'uses' => '\Barryvdh\TranslationManager\Controller@getView'])->middleware(['permission:translate', 'auth']);


Route::get('/search/translations/key', [
    'as' => 'translations.search',
    'middleware' => ['permission:translate', 'auth'],
    'uses' => 'TranslationController@searchKey'
]);

Route::post('/translations/add-description', [
    'as' => 'translations.description',
    'middleware' => ['permission:translate', 'auth'],
    'uses' => 'TranslationController@addDescription'
]);


Route::post('/register', 'RegistrationController@register')->name('user.register');

Route::patch('/user_details/{id}', 'ProfileController@update')->name('profile.user_details');
Route::patch('/change_password/{id}', 'ProfileController@changePassword')->name('changePassword');
Route::patch('/change/user/password/{id}', 'UserController@changePassword')->name('changeUserPassword');


Route::post('/cv_contacts', 'CvController@contacts');
Route::post('/cv_personal', 'CvController@personal');
Route::post('/cv_objective', 'CvController@objective');

resources/views/blog-single.blade.php
@extends('layouts.app')
@section('css')

    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
@endsection
@section('content')
    <section class="blog-single-page">
        <h1 class="text-center">{{$blog->data->title}}</h1>
        {{--<div class="post-author d-flex">--}}
        {{--<img src="{{isset($blog->user->image) ? Storage::disk('')->url($blog->user->image) : '/img/blog-author.png' }}" alt="" class="post-author-img">--}}
        {{--<div class="post-info">--}}
        {{--{{trans('blogs.written_by')}} {{$blog->user->first_name }}  {{$blog->user->last_name}}--}}
        {{--</div>--}}

        {{--</div>--}}

        <div class="w-100">
            <img src="{{Storage::disk('')->url($blog->image)}}" alt="blog image" class="img-fluid w-100">

        </div>
    </section>
    <div class="blog-single-text">

        <div class="blog-content d-flex">
            <div class="share text-center">
                <a href="https://twitter.com/share?url={{route('blog-single',$blog->slug)}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24.598" height="19.679" viewBox="0 0 24.598 19.679">
                        <g transform="translate(0 0)">
                            <path d="M11.736,7380.679a14.147,14.147,0,0,0,14.359-14.139c0-.215,0-.43-.015-.643a10.215,10.215,0,0,0,2.518-2.57,10.193,10.193,0,0,1-2.9.781,5.009,5.009,0,0,0,2.219-2.75,10.15,10.15,0,0,1-3.205,1.208,5.108,5.108,0,0,0-7.141-.216,4.925,4.925,0,0,0-1.46,4.747,14.41,14.41,0,0,1-10.4-5.19,4.925,4.925,0,0,0,1.563,6.631,5.052,5.052,0,0,1-2.291-.62v.062a4.989,4.989,0,0,0,4.049,4.87,5.071,5.071,0,0,1-2.278.086,5.044,5.044,0,0,0,4.714,3.452,10.228,10.228,0,0,1-6.267,2.13,10.533,10.533,0,0,1-1.2-.071,14.452,14.452,0,0,0,7.736,2.229"
                                  transform="translate(-4 -7361)" fill="#006db7" fill-rule="evenodd"/>
                        </g>
                    </svg>
                </a>
                <a href="http://www.facebook.com/sharer.php?u={{route('blog-single',$blog->slug)}}">

                    <svg xmlns="http://www.w3.org/2000/svg" width="10.032" height="20.064" viewBox="0 0 10.032 20.064">
                        <g transform="translate(0 0)">
                            <path d="M335.843,7259.064v-9.029h2.741l.448-4.013h-3.189v-1.954c0-1.034.026-2.06,1.47-2.06h1.462v-2.869a16.4,16.4,0,0,0-2.527-.14c-2.654,0-4.316,1.662-4.316,4.715v2.308H329v4.013h2.933v9.029Z"
                                  transform="translate(-329 -7239)" fill="#006db7" fill-rule="evenodd"/>
                        </g>
                    </svg>
                </a>

                {{--<a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());">--}}

                {{--<svg xmlns="http://www.w3.org/2000/svg" width="16.052" height="20.091" viewBox="0 0 16.052 20.091">--}}
                {{--<path d="M10.984,12.649a.844.844,0,0,1,.024.1c.284,1.615,1.028,2.29,2.453,2.29,2.271,0,4.585-2.819,4.585-5.759,0-3.063-2.467-5.277-6.465-5.277A5.313,5.313,0,0,0,6.006,9.284a3.574,3.574,0,0,0,.754,2.646A1,1,0,1,1,5.4,13.4,5.375,5.375,0,0,1,4,9.284,7.3,7.3,0,0,1,11.58,2c5.06,0,8.471,3.061,8.471,7.284,0,3.969-3.114,7.765-6.591,7.765a4.2,4.2,0,0,1-3.2-1.259l-1.269,5.5a1,1,0,1,1-1.954-.451l3.01-13.042A1,1,0,0,1,12,8.245Z"--}}
                {{--transform="translate(-4 -2)" fill="#006db7"/>--}}
                {{--</svg>--}}
                {{--</a>--}}
            </div>
            <div>
                <div class="blog-p">
                    {!! $blog->data->content !!}
                </div>
                <div class="blog-date">
                    @permission('all_article')
                    {{trans('blogs.originally_published')}}
                    {{trans('months.'.\Carbon\Carbon::parse($blog->created_at)->format('M')).' '.\Carbon\Carbon::parse($blog->created_at)->format('d').','.'  '.  \Carbon\Carbon::parse($blog->created_at)->format('Y H:i')}}
                    <br>
                    @endpermission
                    {{trans('blogs.last_updated')}}
                    {{trans('months.'.\Carbon\Carbon::parse($blog->data->updated_at)->format('M')).' '.\Carbon\Carbon::parse($blog->data->updated_at)->format('d').','.'  '.  \Carbon\Carbon::parse($blog->data->updated_at)->format('Y H:i')}}
                    @permission('all_article')
                    @if(isset($blog->editor))
                        {{trans('blogs.last_updated_by')}}
                        {{$blog->editor->username}}
                    @endif
                    @endpermission
                    @if(\Illuminate\Support\Facades\Auth::check())
                        @if(($blog->user_id == \Illuminate\Support\Facades\Auth::id() &&  \Illuminate\Support\Facades\Auth::user()->can('edit_article')) || \Illuminate\Support\Facades\Auth::user()->can('all_article'))
                            <a class="job-btn btn btn-orange-gradient"
                               href="{{route('blogs.edit',$blog->id)}}">{{trans('blogs.edit')}}</a>
                        @endif
                    @endif
                </div>
            </div>


        </div>


    </div>
    <div class="text-center dont-forget">
        <div class="title">
            {{trans('blogs.dont_forget_to_share')}}
        </div>
        <div class="share">
            <a href="http://www.facebook.com/sharer.php?u={{route('blog-single',$blog->slug)}}">

                <svg xmlns="http://www.w3.org/2000/svg" width="10.032" height="20.064" viewBox="0 0 10.032 20.064">
                    <g transform="translate(0 0)">
                        <path d="M335.843,7259.064v-9.029h2.741l.448-4.013h-3.189v-1.954c0-1.034.026-2.06,1.47-2.06h1.462v-2.869a16.4,16.4,0,0,0-2.527-.14c-2.654,0-4.316,1.662-4.316,4.715v2.308H329v4.013h2.933v9.029Z"
                              transform="translate(-329 -7239)" fill="#006db7" fill-rule="evenodd"/>
                    </g>
                </svg>
            </a>
            {{--<a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());">--}}

            {{--<svg xmlns="http://www.w3.org/2000/svg" width="16.052" height="20.091" viewBox="0 0 16.052 20.091">--}}
            {{--<path d="M10.984,12.649a.844.844,0,0,1,.024.1c.284,1.615,1.028,2.29,2.453,2.29,2.271,0,4.585-2.819,4.585-5.759,0-3.063-2.467-5.277-6.465-5.277A5.313,5.313,0,0,0,6.006,9.284a3.574,3.574,0,0,0,.754,2.646A1,1,0,1,1,5.4,13.4,5.375,5.375,0,0,1,4,9.284,7.3,7.3,0,0,1,11.58,2c5.06,0,8.471,3.061,8.471,7.284,0,3.969-3.114,7.765-6.591,7.765a4.2,4.2,0,0,1-3.2-1.259l-1.269,5.5a1,1,0,1,1-1.954-.451l3.01-13.042A1,1,0,0,1,12,8.245Z"--}}
            {{--transform="translate(-4 -2)" fill="#006db7"/>--}}
            {{--</svg>--}}
            {{--</a>--}}
            <a href="https://twitter.com/share?url={{route('blog-single',$blog->slug)}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24.598" height="19.679" viewBox="0 0 24.598 19.679">
                    <g transform="translate(0 0)">
                        <path d="M11.736,7380.679a14.147,14.147,0,0,0,14.359-14.139c0-.215,0-.43-.015-.643a10.215,10.215,0,0,0,2.518-2.57,10.193,10.193,0,0,1-2.9.781,5.009,5.009,0,0,0,2.219-2.75,10.15,10.15,0,0,1-3.205,1.208,5.108,5.108,0,0,0-7.141-.216,4.925,4.925,0,0,0-1.46,4.747,14.41,14.41,0,0,1-10.4-5.19,4.925,4.925,0,0,0,1.563,6.631,5.052,5.052,0,0,1-2.291-.62v.062a4.989,4.989,0,0,0,4.049,4.87,5.071,5.071,0,0,1-2.278.086,5.044,5.044,0,0,0,4.714,3.452,10.228,10.228,0,0,1-6.267,2.13,10.533,10.533,0,0,1-1.2-.071,14.452,14.452,0,0,0,7.736,2.229"
                              transform="translate(-4 -7361)" fill="#006db7" fill-rule="evenodd"/>
                    </g>
                </svg>
            </a>
        </div>
    </div>


    <section class="blog-boxes related-articles w-100">
        <h3 class="text-center">{{trans('blogs.related_articles')}}</h3>
        <div class="d-flex flex-wrap blog-boxes-content">
            @foreach($related as $item)
                <div class="blog-box">
                    <a href="{{route('blog-single',$item->slug)}}">
                        <img src="{{Storage::disk('')->url($item->image)}}" alt="blogs" class="img-fluid blog-box-img">
                        <div class="blog-box-text">
                            <div class="blog-box-padding">
                                <h6 class="title">{{$item->data->title}}</h6>
                                <span class="date">{{$item->created_at->format('M d, Y')}}</span>
                                <div class="blog-text">
                                    {{$item->data->short_description}}
                                </div>
                            </div>
                            <a href="{{route('blog-single',$item->slug)}}"
                               class="blog-link"> {{trans('blogs.read_more')}}</a>
                        </div>
                    </a>
                </div>
            @endforeach
        </div>
    </section>
@endsection

resources/views/blog.blade.php
@extends('layouts.app')
@section('css')

    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
@endsection
@section('content')

    <section class="blog-page-banner d-flex w-100">
        <div class="position-relative blog">
            @if(isset($first))
                <a href="{{route('blog-single',$first->slug)}}">
                    <img src="{{Storage::disk('')->url($first->image)}}" alt=""
                         class="w-100 img-fluid h-100 object-fit-cover">
                    <div class="hover-gradient">
                        <div class="d-flex justify-content-between align-items-end">
                            <div>
                                <div class="title">{{$first->data->title}}</div>
                                <span class="date">{{$first->created_at->format('M d, Y')}}</span>
                            </div>
                        </div>
                    </div>
                </a>
            @endif
        </div>

    </section>
    <section class="blog-boxes w-100">

        <div class="d-flex flex-wrap blog-boxes-content">
            @foreach($blogs as $item)
            <div class="blog-box">
                <a href="{{route('blog-single',$item->slug)}}">
                    <img src="{{Storage::disk('')->url($item->image)}}" alt="blogs" class="img-fluid blog-box-img">
                    <div class="blog-box-text">
                        <div class="blog-box-padding">
                            <h6 class="title">{{$item->data->title}}</h6>
                            <span class="date">{{$item->created_at->format('M d, Y')}}</span>
                            <div class="blog-text">
                               {{$item->data->short_description}}
                            </div>
                        </div>
                        <a href="{{route('blog-single',$item->slug)}}" class="blog-link"> {{trans('blogs.read_more')}}</a>
                    </div>
                </a>
            </div>

            @endforeach
                {{$blogs->links()}}
        </div>

    </section>
@endsection

resources/views/companySingle.blade.php
@extends('layouts.app')
@section('css')
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="blue-gradient"></div>
    <section class="position-relative company-page">

        <img src="/img/company-bg.svg" alt="" class="company-bg img-fluid">

        <div class="company-page-content">
            @if(isset($user->image))
                <img src="{{Storage::disk('')->url($user->image)}}" alt="" class="img-fluid mb-5">
            @endif
            <h3>{{$company->name}} @if(isset($company->legal_structure) && $company->legal_structure!='other'  && $company->legal_structure!='brand')
                    @if(\Lang::has('legal_structure.'.$company->legal_structure))
                        {{trans('legal_structure.'.$company->legal_structure)}}
                    @else
                        {{$company->legal_structure}}
                    @endif
                @endif
            </h3>
            @if(isset($company->about_company) && $company->about_company!='')
                <h4>{{trans('company.about_us')}}:</h4>
                <p>{!! $company->about_company !!}</p>
            @endif
            @if(Auth::check() && Auth::user()->can('accessAll_announcement'))
                <h4>{{trans('company.contact_us')}}: </h4>

                <address class="company-address">

                    @if(isset($user->address) && count($user->address)!=0)
                        @foreach($user->address as $item)
                            <span class="d-block">
                    {{$item->address}},
                                {{$item->city}}
                                , {{trans('countries.'.$item->country->code)}}</span>
                        @endforeach
                    @endif
                    @if(isset($phone))
                        @foreach($phone as $item)
                            <span class="d-block"><b>{{trans('company.tel')}}:</b>
                        <a href="tel:{{$item['phone']}}">{{$item['phone']}}</a></span>
                        @endforeach

                    @endif
                    @if(isset($user->email))
                        <span class="d-block"><b>{{trans('company.email')}}:</b><a
                                    href="mailto:{{$user->email}}">{{$user->email}}</a></span>
                    @endif
                </address>
            @endif

            <br>
            <br>
            @if(count($user->posted_job)!=0)
                <h4>{{trans('company.working_at')}} {{$company->name}} : </h4>
                <div class="d-flex flex-wrap justify-content-between">
                    @foreach($user->posted_job as $item)
                        @if(isset($item->data))
                            <a href="{{route('jobs',$item->slug)}}" class="company-work d-flex align-items-center">
                                <div>
                                    <p>{{$item->data->title}}</p>
                                    <span>{{$item->data->deadline}}</span>
                                </div>
                                <span class="ml-auto learn-span">{{trans('company.learn_more')}}</span>
                            </a>
                        @endif
                    @endforeach

                </div>
            @endif
        </div>

    </section>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages.blade.php
@extends('layouts.app')
@section('css')
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
@endsection
@section('content')

    <section class="static-page">
        <div class="static-container">
            <h1 class="static-date">{{$page->data->title}}<span>({{trans('pages.last_updated')}}: {{\Carbon\Carbon::parse($page->data->updated_at)->format('Y-m-d H:i')}})</span></h1>
            {!! $page->data->content !!}
        </div>

    </section>

@endsection